### ISSUE TITLE
Equivalents of `msg.sender` and `tx.origin`

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-sc-std#12]
Doing `JSON.parse<string[]>(Context.get_call_stack())` to retrieve the caller of a smart-contract is not convenient and error prone. It would be nice to add less error prone calls. For example we can start by adding the equivalents of `msg.sender` and `tx.origin` in Ethreum (https://docs.soliditylang.org/en/develop/units-and-global-variables.html#block-and-transaction-properties).

**Comment by yvan-sraka** [comment]
@qdrn @z80dev have you checked out https://github.com/massalabs/massa-sc-std/pull/11? Does it tackle a bit this issue?

**Comment by qdrn** [comment]
> @qdrn @z80dev have you checked out #11? Does it tackle a bit this issue?

Yes. It's orthogonal. The idea here would be to have "high level" calls that would essentially return `call_stack[-2]` and `call_stack[0]` (if I'm not mistaken). The address of the caller and the address of the sender of the transaction are probably the two addresses that will be called most so it makes sense to have specific functions.

**Comment by yvan-sraka** [comment]
> Yes. It's orthogonal. The idea here would be to have "high level" calls that would essentially return `call_stack[-2]` and `call_stack[0]` (if I'm not mistaken). The address of the caller and the address of the sender of the transaction are probably the two addresses that will be called most so it makes sense to have specific functions.

Okay, I will add it to this PR!
