### ISSUE TITLE
Pass unserialized args to `call` function

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-sc-std#15]
# Context

Current version of exported function `call` from massa-sc-std module expects serialized parameters in a string like [the following](https://github.com/massalabs/massa-sc-examples/blob/a5cb54bdee8dd10fcef4e58923f784a81bdd1cd2/assembly/create_token.ts#L26):

```javascript
...
call(token1, "transfer", JSON.stringify<TransferArgs>({to: acct2, amount: 50}), 0)
...
```
# Desired solution

Passing arguments without having to serialize parameters like the following:

```javascript
...
call(token1, "transfer", acct2, amount, 0)
...
```

**Comment by gregLibert** [comment]
@yvan-sraka @adrien-zinger What do you think?
@qdrn FYI

**Comment by qdrn** [comment]
I think we all want this. The question is how can we manage to get there ? Any ideas ?

**Comment by gregLibert** [comment]
@yvan-sraka @adrien-zinger any idea?
I'm new to assembly script, but from what I found, function overloading is [not an option](https://github.com/AssemblyScript/assemblyscript/issues/421), nor variadic functions.

Do you have any idea?

**Comment by gregLibert** [comment]
I tested optional generic arguments and it's also rejected by the compiler...
I identify the following solution:

### working around AssemblyScript
The idea is to use a precompilation step that will change the code (like a rust macro).
As long as we are compliant with TypeScript the linter will not yield.

```javascript
...
// declaration
function call(address: string, func: string, call_coins: i64, param1?: T, param2?: U, param3?: V): string {
...
//usage
call(token1, "transfer", 0, acct2, amount)
...
```
### inline map
```javascript
//decalration
function call(address: string, func: string, param: Map<string,string>, call_coins: i64): string {
...
//usage
call(token1, "transfer",
  new Map([
        ["to", "acct2"],
        ["amount", "50"]
    ]),
   0);
...
```
### using function argument

```javascript
//declaration
class Caller {
  address: string;
  func: u32;
  call_coins: string;
 param: Array<string>;

  constructor(a: string, f: string, c:i64) {
    this.address = a;
    this.func = f;
    this.call_coins = c;
this.param = new Array<String>();
  }
  
  With<T>(a: T) Caller {
    this.param.push(string(a));
  }

  Call() string {
...
//usage
let e = new Caller(token1, "transfer", 0)
             .With(acct2)
             .With(50)
             .Call();
...
```
### wrapping calls in object

Using object to wrap calls in business logic like in [this issue](https://github.com/massalabs/massa-sc-examples/issues/10)

**Comment by yvan-sraka** [comment]
I think if one part of your concern is _"how to extend AssemblyScript with custom syntactic sugar"_ one of the technical answer is https://www.sweetjs.org/ :)

**Comment by gregLibert** [comment]
@yvan-sraka can you clarify dev journey?

**Comment by yvan-sraka** [comment]
> @yvan-sraka can you clarify dev journey?

I'm not sure to understand your question, but one way to integrate `sweet.js` to our current architecture would be to add it as `massa-sc-scripts` dependency. What do you think about it?

**Comment by gregLibert** [comment]
Regarding working around AssemblyScript proposal, I was more thinking about using a [precompilation step](https://www.assemblyscript.org/compiler.html#transforms) that would silently modify the code from:
```javascript
...
//usage
call(token1, "transfer", 0, acct2, amount)
...
```
to
```javasscript
...
hidden_call(token1, "transfer", 0, JSON.stringify<TransferArgs>({to: acct2, amount: 50}))
...
```
The file not being impacted, this modification will be transparent to the dev.

**Comment by gregLibert** [comment]
> I'm not sure to understand your question, but one way to integrate sweet.js to our current architecture would be to add it as massa-sc-scripts dependency. What do you think about it?

I'm not sure that adding sweet.js as dependency will be enough. We will need to add a compilation step that will modify the code.
My main fear is that the file itself is updated before compilation, the dev not understanding why...

**Comment by yvan-sraka** [comment]
`sweet.js` (are any macro system) is the pre-compilation step you need :)

**Comment by gregLibert** [comment]
My proposal on this is to use a [tranform](https://www.assemblyscript.org/compiler.html#transforms) to :
#### Change how the smart contracts are generated:
Public functions are not exported anymore, but a decorator, `@sc-public` for instance, is used to mark the function as callable from a remote smart-contract. This function is automatically wrapped by the transformer like the following:

```javascript
...
@sc-public
function execute(a: typeX, b: typeY): typeZ {
...
```
At compilation, [after parsing](https://www.assemblyscript.org/compiler.html#hooks), something like the following function is added by the transformer:
```javascript
...
export function rpc_execute(a: string):string {
   let args = a.split("|");
  return execute(typeX.from(args[0]), typeY.from(args[1])).toString()
}
...
```
#### Change how the remote functions are called

The `call` function instruction is replaced by the transformer:

```javascript
...
//written by dev
let result = call<typeZ>("address", "execute", 0, arg1, arg2);
//change at compilation time
let result = rpc_call<typeZ>("address", "execute", 0, "arg1|arg2"));
...
```

Wdyt?

**Comment by qdrn** [comment]
Looks good from a user perspective. Any remark @yvan-sraka @adrien-zinger @damip ?

**Comment by yvan-sraka** [comment]
My opinion is still that `sweet.js` is a safe hygienic macro engine (you can compare is to rust [`macro_rules!`](https://doc.rust-lang.org/rust-by-example/macros.html)), where [transforms](https://www.assemblyscript.org/compiler.html#transforms) feature of AssemblyScript compiler is an unsafe hook that directly operate on AST (you can compare it to rust [`#[proc_macro]`](https://doc.rust-lang.org/reference/procedural-macros.html#the-proc_macro-crate) in [`span::mixed_site`](https://doc.rust-lang.org/proc_macro/struct.Span.html#method.mixed_site) mode), so I will always go for the safe choice if it has enough semantic power to encapsulate well our problem! :slightly_smiling_face:

**Comment by yvan-sraka** [comment]
Why not ask advices on the [AssemblyScript community Discord](https://discord.com/invite/assemblyscript)?!

**Comment by yvan-sraka** [comment]
Because one simple, less overkill solution, is just to hide the serialization in the `massa-sc-std` like I did here https://github.com/massalabs/massa-sc-std/pull/11/files

**Comment by yvan-sraka** [comment]
Because one simple, less overkill solution, is just to hide the serialization in the `massa-sc-std` like I did here https://github.com/massalabs/massa-sc-std/pull/11/files

**Comment by gregLibert** [comment]
> It's a really hard thing to maintain a good library that doesn't contain his own features and rely on multiple compilation's hooks. We already did one for the famous includes_base64 and it's already the hardest thing to explain to users rofl

Maybe we should integrate it in the same transformer!
