### ISSUE TITLE
Automatically release the npm package when creating a new tag

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa-sc-std#17]
## Context

It would be nice to automate the npm package release so that it is created when we make a github release on the project.

## To Do

- [x] Make some research on the best way to do this
- [x] Integrate it to the project

**Comment by yvan-sraka** [comment]
Already implemented here https://github.com/massalabs/massa-sc-std/blob/main/.github/workflows/npm-publish.yml just need to fix `npm ci` build stage https://github.com/massalabs/massa-sc-std/actions/runs/2063236734

**Comment by qdrn** [comment]
I believe it will be fixed by pushing the `package-lock.json`. Anything else we should worry about @yvan-sraka ?

**Comment by yvan-sraka** [comment]
> I believe it will be fixed by pushing `package-lock.json`. Anything else we should worry about @yvan-sraka ?

Done here https://github.com/massalabs/massa-sc-std/pull/11/commits/ee210815b488c548221241acaafec7da761295e8 :)

**Comment by yvan-sraka** [comment]
> I believe it will be fixed by pushing `package-lock.json`. Anything else we should worry about @yvan-sraka ?

Done here https://github.com/massalabs/massa-sc-std/pull/11/commits/ee210815b488c548221241acaafec7da761295e8 :)
