### ISSUE TITLE
`get_call_stack` isn't exported anymore

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-sc-std#19]
Is that made in purpose ? and why ?

**Comment by yvan-sraka** [comment]
Yes it was obsoleted by https://github.com/massalabs/massa-sc-std/issues/12 suggested by @qdrn :)

**Comment by AurelienFT** [comment]
The problem is that on the cat designed by @qdrn he uses len - 1 : https://github.com/massalabs/cryptocat/blob/main/src/helloworld.ts#L17 and there is no way to do it now ? cc @qdrn

**Comment by qdrn** [comment]
> The problem is that on the cat designed by @qdrn he uses len - 1 : https://github.com/massalabs/cryptocat/blob/main/src/helloworld.ts#L17 and there is no way to do it now ? cc @qdrn

Yeah. I think there are still use cases. This one in particular. Maybe some other weird ones ?

In any case, I'm still able to do `Context.get_call_stack()` even though the function is not exported anymore. For instance in the following case:
```ts
import { Context } from "massa-sc-std"

export function main(_: string): void {
    const addresses = Context.get_call_stack();
    print(addresses[0]);
}
```

**Comment by qdrn** [comment]
However, I had to change `get_call_stack` from:
```ts
function get_call_stack(): string[] {
    return (<JSON.Arr>(JSON.parse(assembly_script_get_call_stack()))).valueOf().map(x => x.toString());
}
```
to
```ts
function get_call_stack(): string[] {
    return (<JSON.Arr>(JSON.parse(assembly_script_get_call_stack()))).valueOf().map<string>(x => x.toString());
}
```
otherwise I get:
```
ERROR TS1140: Type argument expected.

         return (<JSON.Arr>(JSON.parse(assembly_script_get_call_stack()))).valueOf().map(x => x.toString());
                                                                                        ^
 in ~lib/massa-sc-std/index.ts(244,88)
```
