### ISSUE TITLE
Compilation fails with version 3.0.0

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa-sc-std#20]
I get the following error when I'm compiling a SC importing `Context`:

```javascript
ERROR TS1140: Type argument expected.

         return (<JSON.Arr>(JSON.parse(assembly_script_get_call_stack()))).valueOf().map(x => x.toString());
                                                                                        ^
 in ~lib/massa-sc-std/index.ts(244,88)
```

**Comment by yvan-sraka** [comment]
It seems related to https://github.com/massalabs/massa-sc-std/issues/19 right?

**Comment by AurelienFT** [comment]
> It seems related to #19 right?

No. It's different. This compile error prevent to use the whole Context namespace as soon as you import and you use it you have this error
