### ISSUE TITLE
Better CI

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-sc-std#9]
Is it possible to ensure that https://github.com/massalabs/massa-sc-template (and other relevant repos) use the latest published version of sc-std (and that it works ofc) ?

cc @yvan-sraka

**Comment by yvan-sraka** [comment]
> Is it possible to ensure that https://github.com/massalabs/massa-sc-template (and other relevant repos) use the latest published version of sc-std (and that it works ofc) ?
> 
> cc @yvan-sraka

Why is the purpose of ensuring that? Do we not prefer to keep control of that manually?

**Comment by qdrn** [comment]
Right now if we change `massa-sc-std` it might breaks things elsewhere. With the number of repos using `massa-sc-std` it's hard to keep track of what has been updated or not. Maybe that's not the good way to do it but at some point we must ensure that examples are always properly working, templates are up to date, etc...

**Comment by yvan-sraka** [comment]
That's for sure the purpose of versioning and to use versioned dependencies to be able to update `massa-sc-std` and to upgrade progressively other repositories, but I get your point, and we could integrate this simple logic in CI:

```shell
yarn remove massa-sc-std
yarn install massa-sc-std
# check if package-lock.json changed
```
